### ISSUE TITLE
Problems with latest @types/node

### ISSUE THREAD

**Issue by webleaf** [NativeScript/nativescript-dev-webpack#679]
After updating to `@types/node@latest` produces errors, when do `--bundle`

```
ERROR in [at-loader] ./node_modules/tns-core-modules/module.d.ts:1:13 
    TS2451: Cannot redeclare block-scoped variable 'global'.

ERROR in [at-loader] ./node_modules/tns-core-modules/tns-core-modules.d.ts:22:13 
    TS2451: Cannot redeclare block-scoped variable 'require'.

ERROR in [at-loader] ./node_modules/tns-core-modules/tns-core-modules.d.ts:33:13 
    TS2451: Cannot redeclare block-scoped variable '__dirname'.

ERROR in [at-loader] ./node_modules/tns-core-modules/tns-core-modules.d.ts:34:13 
    TS2451: Cannot redeclare block-scoped variable '__filename'.

ERROR in [at-loader] ./node_modules/tns-core-modules/tns-core-modules.d.ts:36:13 
    TS2451: Cannot redeclare block-scoped variable 'module'.

ERROR in [at-loader] ./node_modules/tns-core-modules/tns-core-modules.d.ts:38:13 
    TS2451: Cannot redeclare block-scoped variable 'exports'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:197:15 
    TS2451: Cannot redeclare block-scoped variable 'global'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:200:15 
    TS2451: Cannot redeclare block-scoped variable '__filename'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:201:15 
    TS2451: Cannot redeclare block-scoped variable '__dirname'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:243:15 
    TS2451: Cannot redeclare block-scoped variable 'require'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:256:15 
    TS2451: Cannot redeclare block-scoped variable 'module'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:259:15 
    TS2451: Cannot redeclare block-scoped variable 'exports'.
```
Downgrading to `@types/node@10.9.4` resolve the issue.

**Comment by NickIliev** [comment]
@webleaf which version is `latest`. The issue seems related to [this one ](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29280)which was fixed with a new version couple of days ago

**Comment by webleaf** [comment]
@NickIliev version was `@types/node@10.11.2`, but with `@types/node@10.11.3` still exist and now looks so:
```
ERROR in [at-loader] ./node_modules/tns-core-modules/module.d.ts:1:13 
    TS2451: Cannot redeclare block-scoped variable 'global'.

ERROR in [at-loader] ./node_modules/tns-core-modules/tns-core-modules.d.ts:33:13 
    TS2451: Cannot redeclare block-scoped variable '__dirname'.

ERROR in [at-loader] ./node_modules/tns-core-modules/tns-core-modules.d.ts:34:13 
    TS2451: Cannot redeclare block-scoped variable '__filename'.

ERROR in [at-loader] ./node_modules/tns-core-modules/tns-core-modules.d.ts:38:13 
    TS2451: Cannot redeclare block-scoped variable 'exports'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:197:15 
    TS2451: Cannot redeclare block-scoped variable 'global'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:200:15 
    TS2451: Cannot redeclare block-scoped variable '__filename'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:201:15 
    TS2451: Cannot redeclare block-scoped variable '__dirname'.

ERROR in [at-loader] ./node_modules/@types/node/index.d.ts:259:15 
    TS2451: Cannot redeclare block-scoped variable 'exports'.
```

**Comment by NickIliev** [comment]
@webleaf the issue solution is reverting the `const` declarations from @types/node just as done in this [partial fix](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29267/files).

After installing the `@types/node` package I was able to build by opening `node_modules/@types/node/index.d.ts` file and chainging the `const` declarations to `var` for the following lines

Modified code
```TS
declare var global: NodeJS.Global;


declare var __filename: string;
declare var __dirname: string;

declare var exports: any;
```

Original in @types/node 10.11.3
```TS
declare const global: NodeJS.Global;

declare const __filename: string;
declare const __dirname: string;

declare const exports: any;
```

**Comment by webleaf** [comment]
resolved in `@types/node 10.11.4`
