### ISSUE TITLE
Error after install web pack on existing project

### ISSUE THREAD

**Issue by dzfweb** [NativeScript/nativescript-dev-webpack#81]
I've an existing app and i'v tried to use nativescript-dev-webpack but some errors has occured.

It's my first project that i'm trying to use web pack, and i don't know how to fix my issues to continue using.

```

ERROR in Type RadSideDrawerComponent in C:/dev/fm-transportes/src/FM.Transportes/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts is part of the declarations of 2 modules: NativeScriptUISideDrawerModule in C:/dev/fm-transportes/src/FM.Transportes/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts and SharedModule in C:/dev/fm-transportes/src/FM.Transportes/app/modules/shared/shared.module.ts! Please consider moving RadSideDrawerComponent in C:/dev/fm-transportes/src/FM.Transportes/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts to a higher module that imports NativeScriptUISideDrawerModule in C:/dev/fm-transportes/src/FM.Transportes/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts and SharedModule in C:/dev/fm-transportes/src/FM.Transportes/app/modules/shared/shared.module.ts. You can also create a new NgModule that exports and includes RadSideDrawerComponent in C:/dev/fm-transportes/src/FM.Transportes/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts then import that NgModule in NativeScriptUISideDrawerModule in C:/dev/fm-transportes/src/FM.Transportes/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts and SharedModule in C:/dev/fm-transportes/src/FM.Transportes/app/modules/shared/shared.module.ts.

ERROR in ../~/nativescript-angular/router/ns-module-factory-loader.js
Module not found: TypeError: Cannot convert undefined or null to object
 @ ../~/nativescript-angular/router/ns-module-factory-loader.js 23:15-40
 @ ../~/nativescript-angular/router.js
 @ ./vendor.ts

ERROR in ./modules/pack.address/pack.address.component.ts
Module not found: Error: Can't resolve 'nativescript-directions' in 'C:\dev\fm-transportes\src\FM.Transportes\app\modules\pack.address'
 @ ./modules/pack.address/pack.address.component.ts 13:17-51
 @ ./modules/app.module.ts
 @ ./main.ts

ERROR in ./modules/shared/services/database.service.ts
Module not found: Error: Can't resolve 'nativescript-sqlite' in 'C:\dev\fm-transportes\src\FM.Transportes\app\modules\shared\services'
 @ ./modules/shared/services/database.service.ts 1:13-43
 @ ./modules/shared/index.ts
 @ ./modules/app.module.ts
 @ ./main.ts

ERROR in ../~/nativescript-localstorage/localstorage.js
Module not found: Error: Can't resolve 'file-system/file-system-access.js' in 'C:\dev\fm-transportes\src\FM.Transportes\node_modules\nativescript-localstorage'
 @ ../~/nativescript-localstorage/localstorage.js 9:25-69
 @ ./modules/shared/services/session.service.ts
 @ ./modules/shared/index.ts
 @ ./modules/app.module.ts
 @ ./main.ts
```

**Comment by sis0k0** [comment]
Hi @dzfweb,

I'll probably need some information about your app in order to help. Just a shot in the dark - you should use the next tag `nativescript-telerik-ui` and if you have the `SIDEDRAWER_DIRECTIVES` in the declarations of your module, replace that with an import of the `NativeScriptUISideDrawerModule`.

``` ts
import { NativeScriptUISideDrawerModule } from 'nativescript-telerik-ui/sidedrawer/angular';
...
@NgModule({
  imports: [
    NativeScriptUISideDrawerModule
  ]
...
})
...
```

If that's not the case, please share your `package.json` and the code where you are using telerik-ui.

**Comment by dzfweb** [comment]
Here is my package.json:
```

{
  "description": "FM Transportes",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "FM Transportes",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.FMTransportes",
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.5",
    "@angular/compiler": "2.4.5",
    "@angular/core": "2.4.5",
    "@angular/forms": "2.4.5",
    "@angular/http": "2.4.5",
    "@angular/platform-browser": "2.4.5",
    "@angular/platform-browser-dynamic": "2.4.5",
    "@angular/router": "3.4.5",
    "email-validator": "1.0.4",
    "nativescript-angular": "1.4.0",
    "nativescript-camera": "0.0.8",
    "nativescript-directions": "^1.0.4",
    "nativescript-drawingpad": "^1.1.2",
    "nativescript-intl": "0.0.10",
    "nativescript-local-notifications": "^1.2.1",
    "nativescript-localstorage": "^1.1.0",
    "nativescript-sqlite": "^1.1.2",
    "nativescript-telerik-ui": "^1.5.1",
    "nativescript-theme-core": "1.0.2",
    "nativescript-toast": "^1.4.5",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "^2.5.1"
  },
  "devDependencies": {
    "babel-traverse": "6.18.0",
    "babel-types": "6.18.0",
    "babylon": "6.13.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "~2.1.0",
    "zone.js": "~0.7.2",
    "webpack": "2.2.0",
    "webpack-sources": "~0.1.3",
    "copy-webpack-plugin": "~3.0.1",
    "raw-loader": "~0.5.1",
    "nativescript-css-loader": "~0.26.0",
    "resolve-url-loader": "~1.6.0",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "@angular/compiler-cli": "~2.4.3",
    "@ngtools/webpack": "1.2.4",
    "htmlparser2": "~3.9.2"
  },
  "scripts": {
    "clean-android": "tns clean-app android",
    "clean-ios": "tns clean-app ios",
    "prewebpack-android": "npm run clean-android",
    "prewebpack-ios": "npm run clean-ios",
    "webpack-android": "webpack --config=webpack.android.js --progress",
    "webpack-ios": "webpack --config=webpack.ios.js --progress",
    "prestart-android-bundle": "npm run webpack-android",
    "prestart-ios-bundle": "npm run webpack-ios",
    "start-android-bundle": "tns run android --bundle --disable-npm-install",
    "start-ios-bundle": "tns run ios --bundle --disable-npm-install",
    "prebuild-android-bundle": "npm run webpack-android",
    "prebuild-ios-bundle": "npm run webpack-ios",
    "build-android-bundle": "tns build android --bundle --disable-npm-install",
    "build-ios-bundle": "tns build ios --bundle --disable-npm-install"
  }
}
```

about the importing of nativescript-telerik-ui/sidedrawer/angular, my code was importing SIDEDRAWER_DIRECTIVES in declarations. I changed to your sugesttion and i'll test.

**Comment by sis0k0** [comment]
I'm assuming that you also changed your `nativescript-telerik-ui` version to next.

The other error appears because you need to use `templateUrl` and `styleUrls` that are relative to the current file instead of absolute. Also you need to add `moduleId` to the component. For example, the component you shared should look like that:

``` ts
@Component({
    moduleId: module.id,
    selector: 'side-drawer-page',
    templateUrl: './side-drawer-page.component.html',
    styleUrls: ['./side-drawer-page.component.css'],
})
...
```
Here I assume that `side-drawer-page.component.html` and `side-drawer-page.component.css` are in the some directory as the component file.

**Comment by dzfweb** [comment]
I adjusted all my components to use relative paths as you mentioned and the first error has solved.
But now i'm getting new others errors:
```

ERROR in Template parse errors:
'StackLayout' is not a known element:
1. If 'StackLayout' is an Angular component, then verify that it is part of this module.
2. If 'StackLayout' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.


ERROR in ../~/nativescript-angular/router/ns-module-factory-loader.js
Module not found: TypeError: Cannot convert undefined or null to object
 @ ../~/nativescript-angular/router/ns-module-factory-loader.js 23:15-40
 @ ../~/nativescript-angular/router.js
 @ ./vendor.ts

ERROR in ./modules/pack.address/pack.address.component.ts
Module not found: Error: Can't resolve 'nativescript-directions' in 'C:\dev\fm-transportes\src\FM.Transportes\app\modules\pack.address'
 @ ./modules/pack.address/pack.address.component.ts 13:17-51
 @ ./modules/app.module.ts
 @ ./main.ts

ERROR in ./modules/shared/services/database.service.ts
Module not found: Error: Can't resolve 'nativescript-sqlite' in 'C:\dev\fm-transportes\src\FM.Transportes\app\modules\shared\services'
 @ ./modules/shared/services/database.service.ts 1:13-43
 @ ./modules/shared/index.ts
 @ ./modules/app.module.ts
 @ ./main.ts

ERROR in ../~/nativescript-localstorage/localstorage.js
Module not found: Error: Can't resolve 'file-system/file-system-access.js' in 'C:\dev\fm-transportes\src\FM.Transportes\node_modules\nativescript-localstorage'
 @ ../~/nativescript-localstorage/localstorage.js 9:25-69
 @ ./modules/shared/services/session.service.ts
 @ ./modules/shared/index.ts
 @ ./modules/app.module.ts
 @ ./main.ts
```

I've followed the errors sugestion, and added CUSTOM_ELEMENTS_SCHEMA to the schemas in my module, but the errors still occuring.

**Comment by dzfweb** [comment]
For the first error with invalid StackLayout element, solved doing this:
#https://github.com/NativeScript/nativescript-dev-webpack/issues/33#issuecomment-266150019

What about the others?

**Comment by dzfweb** [comment]
Solved the following error:

`ERROR in Could not resolve "C:\dev\fm-transportes\src\FM.Transportes\app\app.module" from "C:\dev\fm-transportes\src\FM.Transportes\app\app.module".`

by moving the app.module to the root of the app, and then removing the ./modules from the import line.

Could you help me with the others errors?

**Comment by sis0k0** [comment]
Unfortunately, the later errors are caused by some plugins. For the `nativescript-directions` plugin - it is fixed on github, but it's not published on npm yet. You can install it from github with the following command:

```
npm install EddyVerbruggen/nativescript-directions
```

I will make a PR with some compatibility fixes for the other plugins - `nativescript-sqlite` and `localstorage` later today and write in this issue.

**Comment by dzfweb** [comment]
I've installed from the github as you mentioned using `npm install EddyVerbruggen/nativescript-directions` but the error for nativescript-directions still occurring.

Anyway, thank you a lot for your helping with my issue.

**Comment by dzfweb** [comment]
The first error was solved on version 1.0.5 of nativescript-directions
#https://github.com/EddyVerbruggen/nativescript-directions/issues/10#issuecomment-282080624

**Comment by abhayastudios** [comment]
@sis0k0 I am having similar issues with the [nativescript-telephony](https://github.com/roblav96/nativescript-telephony/issues/3). Any advice how to fix it?

**Comment by dzfweb** [comment]
After fixed all plugins, i finally finnaly got build with webpack.

But now, i'm getting an execution error :/

![screenshot_57](https://cloud.githubusercontent.com/assets/10212321/23326351/78e2421c-fadb-11e6-9a56-c9e615361ff3.png)

**Comment by sis0k0** [comment]
Hey @dzfweb,
Do you have a ´main.aot.ts´ file? If not, please check out (this)[https://github.com/NativeScript/nativescript-dev-webpack/issues/49] thread.

**Comment by dzfweb** [comment]
@sis0k0 thank you!!!! Everything is ok now!!

**Comment by sis0k0** [comment]
Hi @dzfweb,

Sorry for the late reply. Just a few suggestions - the module paths should be relative to `app-routing.ts` and the modules should be exported manually (not with the default keyword) like that:

``` ts
@NgModule({
...
})
export class LoginModule {
...
}
```

If that doesn't help, please share one of your module files. I'm also assuming that you haven't changed your `package.json`.

**Comment by dzfweb** [comment]
Hi @sis0k0, i moved the LoginModule to the same path of app-routing.ts, but the error was similar.

`Cannot find module '/data/data/org.nativescript.FMTransportes/files/app/./login.module'.`

i tried change the module declaration in in app-routing to `loadChildren: "login.module#LoginModule",` but the build failed.

**app.module.ts**
```
import { NgModule, NO_ERRORS_SCHEMA, LOCALE_ID, NgModuleFactoryLoader } from '@angular/core';
import { NativeScriptModule } from "nativescript-angular/platform";
import { NativeScriptRouterModule } from "nativescript-angular/router";
import { routing } from './app-routing.module';
import { AppComponent } from './app.component';
import { CustomModuleLoader } from "./custom.module.loader";

@NgModule({
  providers: [
    { provide: NgModuleFactoryLoader, useClass: CustomModuleLoader },
    { provide: LOCALE_ID, useValue: "pt-BR" }
  ],
  imports: [
    NativeScriptModule,
    NativeScriptRouterModule,
    routing
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule { }

```

**app-routing.ts**
```
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';

const routes = [
  // { path: "", redirectTo: "login", pathMatch: 'full' },
  {
    path: "",
    loadChildren: "./login.module#LoginModule",
  },
  {
    path: "package",
    loadChildren: "./client.module#ClientModule",
  }
];

export const routing = NativeScriptRouterModule.forRoot(routes);
```

**login.module.ts**
```
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule} from "nativescript-angular/nativescript.module";
import { NativeScriptRouterModule } from "nativescript-angular/router";
import { LoginService, SessionService } from './modules/shared/';
import { NativeScriptFormsModule } from "nativescript-angular/forms";
import { NativeScriptHttpModule } from "nativescript-angular/http";
import { routes } from "./login.routes";

import { LoginComponent } from "./login/login.component";

@NgModule({
    imports: [
        NativeScriptModule,
        NativeScriptRouterModule,
        NativeScriptRouterModule.forChild(routes),
        NativeScriptFormsModule, 
        NativeScriptHttpModule
    ],
    providers: [
      LoginService,
      SessionService
    ],
    declarations: [LoginComponent],
    schemas: [NO_ERRORS_SCHEMA]
})
export class LoginModule {
    constructor() { console.log("login module");}
}
```

**Comment by sis0k0** [comment]
Can you please share your `CustomModuleLoader` too? Also, now you can use the `NSModuleFactoryLoader` from `nativescript-angular/router` for lazy-loaded routes.

**Comment by dzfweb** [comment]
**custom.module.loader.ts**
```
import {
    Injectable,
    Compiler,
    NgModuleFactory,
    NgModuleFactoryLoader
} from "@angular/core";

import { path, knownFolders } from "file-system";

const SEPARATOR = "#";

@Injectable()
export class CustomModuleLoader implements NgModuleFactoryLoader {

    constructor(private compiler: Compiler) {
    }

    load(path: string): Promise<NgModuleFactory<any>> {
        let {modulePath, exportName} = this.splitPath(path);

        let loadedModule = require(modulePath)[exportName];
        if (!loadedModule) {
            throw new Error(`Cannot find "${exportName}" in "${modulePath}"`);
        }

        return this.compiler.compileModuleAsync(loadedModule);
    }

    private splitPath(path: string): {modulePath: string, exportName: string} {
        let [modulePath, exportName] = path.split(SEPARATOR);
        modulePath = getAbsolutePath(modulePath);

        if (typeof exportName === "undefined") {
            exportName = "default";
        }

        return {modulePath, exportName};
    }
}

function getAbsolutePath(relativePath: string) {
    return path.normalize(path.join(knownFolders.currentApp().path, relativePath));
}```

**Comment by dzfweb** [comment]
i'd changed to NSModuleFactoryLoader and works again. 
@sis0k0 I don't even know how to thank you, you were very helpful. Thanks

**Comment by sis0k0** [comment]
Sure, no problem. Can we close this now?

**Comment by dzfweb** [comment]
Sure, thank you again. 👏

**Comment by hiddencaliber** [comment]
Hi dzfweb,
I am facing similar issues. Do you mind sharing a working example for this use case ?
Please let me know.

Though this post helped me lot fixing other issue.

Thanks,

**Comment by dzfweb** [comment]
which of those problems did you mean?
Can you explain in detail @hiddencaliber ?

**Comment by hiddencaliber** [comment]
I am actually trying to lazy load one of the module, but getting this weird error where it complains about Cannot find module 'http' in vendor.js file.

I am trying to make a sample project since I cannot share my actual code under security policy.
Meanwhile, could you please share if you have any project ?

Thanks for such a prompt response. Appreciate a lot!

**Comment by monikagupta78** [comment]
@dzfweb - I am also facing same issue related to nativescript-directions plugin. I installed using  tns plugin add nativescript-directions and can see it is added in the node-modules folder and in VS code also , I am able to  import Directions class etc.

But while trying to run ng serve, I am getting this error:
ERROR in ./src/app/directions/directions.component.ts
Module not found: Error: Can't resolve 'nativescript-directions' in 'D:\projects\ng-maps\src\app\directions'
I am using angular 6 and version of nativescript-directions module is 1.2.0.

Any pointers pls?
Thanks
