### ISSUE TITLE
[Angular] HMR restarts the application when modifying the code of linked plugin

### ISSUE THREAD

**Issue by DimitarTodorov** [NativeScript/nativescript-dev-webpack#938]
**Environment**
 - CLI: 5.4.1
 - Cross-platform modules: 5.4.0
 - Android Runtime: 5.4.0
 - iOS Runtime: 5.4.0
 - Plugin(s): nativescript-datetimepicker
  
**To Reproduce**
1. Clone the [nativescript-datetimepicker plugin](https://github.com/NativeScript/nativescript-datetimepicker)
2. Build the plugin: `cd src && npm run build`
3. Run the demo-angular app `tns run android`
4. Open the src/ui/date-picker-field.common.ts and add `defaultValue: new Date(),` on dateProperty field. 
5. Save the file and wait for HMR to sync changes

**Actual behavior**
The changes are applied but the App is Restarted.

**Expected behavior**
The app should not restart.

**Sample project**
The demo-angular app from the repo.

**Additional context**
```
JS: ERROR Error: Uncaught (in promise): Error: Cannot find 'HomeModule' in '~/app/home/home.module'
JS: Error: Cannot find 'HomeModule' in '~/app/home/home.module'
JS:     at checkNotEmpty (file:///data/data/org.nativescript.datetimepicker.demong/files/app/vendor.js:60879:15) [angular]
JS:     at file:///data/data/org.nativescript.datetimepicker.demong/files/app/vendor.js:60856:44 [angular]
JS:     at Object.onInvoke (file:///data/data/org.nativescript.datetimepicker.demong/files/app/vendor.js:59830:33) [angular]
JS:     at file:///data/data/org.nativescript.datetimepicker.demong/files/app/vendor.js:86481:34 [angular]
JS:     at Object.onInvokeTask (file:///data/data/org.nativescript.datetimepicker.demong/files/app/vendor.js:59821:33) [angular]
JS:     at Function.drainMicroTaskQueue (file:///data/data/org.nativescript.datetimepicker.demong/files/app/vendor.js:86193:35) [<root>]
JS:     at NativeScriptPlatformRef.push.../node_modules/nativescript-angular/platform-common.js.NativeScriptPlatformRef._livesync (file:///data/data/org.nativescript.da...
```

**Comment by DimitarTachev** [comment]
It's already fixed in `nativescript-angular@rc`

**Comment by DimitarTodorov** [comment]
Confirm that the fix in nativescript-angular@rc and @next is valid.

**Comment by Thor-** [comment]
I have two android devices 4.4.2 and 7.0
And this issue still actual for android 4.4.2. `nativescript-angular@rc` didn't helped

**Comment by DimitarTachev** [comment]
Hi @Thor, 

Most probably you are using NativeScript 5.4. We've made a lot of improvements in the plugin development for NativeScript 6.0.0.

I suggest you try `nativescript-dev-webpack@next` and `nativescript@next` (you will have to delete your `hooks` folder and the `webpack.config`) or wait a few days for the official 6.0 Release Candidate and the update instructions.

If you try still have some issues with NativeScript 6.0, please open a new issue following the issue template.
